export const PERFORMANCE_REPETITIONS = Number(process.env.KANVANA_PERF_RUNS || 3);
export const MOVES_PER_REPETITION = 5;
export const PERFORMANCE_CALIBRATION = process.env.KANVANA_PERF_CALIBRATE === '1';

// Structural metrics (node counts, live cards, render counts, crashes) reproduce
// exactly run to run, so their budgets sit just above baseline. Wall-clock and heap
// metrics swing with runner load, so their budgets only trip on a material
// (roughly 2x) regression. See docs/spec/testing.md for the recorded baseline.
export const PERFORMANCE_SCENARIOS = [
  {
    taskCount: 400,
    view: 'standard',
    baseline: {
      fixtureBackfillMs: 43.2,
      startupMs: 1099.2,
      taskDropLatencyMs: 2340.86,
      jsHeapUsedMb: 5.96,
      retainedDomNodes: 17432,
      liveDomNodes: 5483,
      detachedDomNodes: 11949,
      liveTaskCards: 205,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 5,
      browserCrashEvents: 0,
    },
    budget: {
      fixtureBackfillMs: 200,
      startupMs: 3000,
      taskDropLatencyMs: 6000,
      jsHeapUsedMb: 14,
      retainedDomNodes: 18300,
      liveDomNodes: 5800,
      detachedDomNodes: 12600,
      liveTaskCards: 210,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 5,
      browserCrashEvents: 0,
    },
  },
  {
    taskCount: 1000,
    view: 'standard',
    baseline: {
      fixtureBackfillMs: 48,
      startupMs: 1080.6,
      taskDropLatencyMs: 5870.15,
      jsHeapUsedMb: 7.49,
      retainedDomNodes: 32972,
      liveDomNodes: 10043,
      detachedDomNodes: 22929,
      liveTaskCards: 445,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 5,
      browserCrashEvents: 0,
    },
    budget: {
      fixtureBackfillMs: 250,
      startupMs: 3200,
      taskDropLatencyMs: 12000,
      jsHeapUsedMb: 16,
      retainedDomNodes: 34700,
      liveDomNodes: 10600,
      detachedDomNodes: 24100,
      liveTaskCards: 450,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 5,
      browserCrashEvents: 0,
    },
  },
  {
    taskCount: 400,
    view: 'swimlane',
    baseline: {
      fixtureBackfillMs: 20.2,
      startupMs: 839.2,
      taskDropLatencyMs: 1432.2,
      jsHeapUsedMb: 6.45,
      retainedDomNodes: 25543,
      liveDomNodes: 4696,
      detachedDomNodes: 20847,
      liveTaskCards: 160,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 10,
      browserCrashEvents: 0,
    },
    budget: {
      fixtureBackfillMs: 200,
      startupMs: 2500,
      taskDropLatencyMs: 3600,
      jsHeapUsedMb: 14,
      retainedDomNodes: 26900,
      liveDomNodes: 5000,
      detachedDomNodes: 21900,
      liveTaskCards: 165,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 10,
      browserCrashEvents: 0,
    },
  },
  {
    taskCount: 1000,
    view: 'swimlane',
    baseline: {
      fixtureBackfillMs: 45.9,
      startupMs: 1350.5,
      taskDropLatencyMs: 2405.22,
      jsHeapUsedMb: 8.8,
      retainedDomNodes: 55843,
      liveDomNodes: 9256,
      detachedDomNodes: 46587,
      liveTaskCards: 400,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 10,
      browserCrashEvents: 0,
    },
    budget: {
      fixtureBackfillMs: 250,
      startupMs: 3600,
      taskDropLatencyMs: 6000,
      jsHeapUsedMb: 18,
      retainedDomNodes: 58700,
      liveDomNodes: 9800,
      detachedDomNodes: 49000,
      liveTaskCards: 405,
      startupBoardRenders: 1,
      steadyStateBoardRenders: 10,
      browserCrashEvents: 0,
    },
  },
];
